
<div>
    <h1>Sobre nós</h1>
    <h3>Nossa missão</h3>
    <p>
        Nosso serviço visa conectar vendedores, fornecedores de serviços à clientes,
        por meio de classificados nos quais fornecemos a divulgação.
    </p>
    <br>
    <p>
        O Vendeu! não se responsabiliza pelos anúncios feitos pelos anúnciantes, visto
        que não intermediamos negociações, todo e qualquer anúncio feito é de responsabilidade
        de seu criador.
    </p>
</div>
