<section>
    <div>
        <form action="/register-user" method="POST">
            <fieldset class="usrRegisterForms" id="userRegister">
                <legend>Cadastro</legend>
                <input type="text" value=""name="name" placeholder="Nome">
                <input type="text" value="" name="surname" placeholder="Sobrenome completo">
                <input type="email" value="" name="email" placeholder="Email">
                <input type="text" value="" name="username" placeholder="Nome de usuário">
                <input type="password" value="" name="passwd" placeholder="Senha">
            </fieldset>

            <fieldset class="usrRegisterForms">
                <button type="submit">Enviar</button>
            </fieldset>
        </form>
        <?php if($this->view->registerError) { ?>
            <div id="formError">
                <small>* Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
            </div>
        <?php } ?>
    </div>
</section>