<section class='showOff'>
<section>
    <h1>Meus anúncios</h1>
</section>
<?php foreach($this->view->userItens as $post) { ?>
				<div class="itemArea">
                <?php

                $dirname = $post['anouncePath'];
                
                $filenames = glob("$dirname*.{jpg,jpeg,png,gif}", GLOB_BRACE);

                foreach ($filenames as $filename)
                {
                    ?>
                    
                    <div class="portrait" onclick="openModal(this)">
                        <img class="itemImage" src="<?php 
                        $filename = str_replace('../public', '', $filename);            
                        echo $filename ?>" />
                    </div>
                <?php }?>

					<div class="itemInfo">
                        <h2><span class="itemName">Nome:</span> <?=$post['name']?></h2>
                        <p><span class="itemDescription">Descrição do item:</span> <?=$post['description']?></p>
                        <p class="itemPrice">R$<?=$post['value']?>,00</p>
                        <span class="date"><?= $post['postDate'] ?></span>
                        <form id="multForm" method="post">
                            <input type="hidden" name="postId" value=<?= $post['id'] ?>>
                            <input type="button" onclick="submitForm('deletePost')" value="Excluir" />
                            <input type="button" onclick="submitForm('editPost')" value="Editar" />
                        </form>
						<br />
                    </div>
                </div>
<?php } ?>
</section>

<script type="text/javascript">
    function submitForm(action) {
        var form = document.getElementById('multForm');
        form.action = action;
        form.submit();
    }
</script>