<section class='showOff'>
<section>
    <h1>Meus anúncios</h1>
</section>
<?php foreach($this->view->userItens as $post) { ?>
				<div class="itemArea">
                <?php

                $dirname = $post['anouncePath'];
                
                $filenames = glob("$dirname*.{jpg,jpeg,png,gif}", GLOB_BRACE);

                foreach ($filenames as $filename)
                {
                    ?>
                    
                    <div class="portrait" onclick="openModal(this)">
                        <img class="itemImage" src="<?php 
                        $filename = str_replace('../public', '', $filename);            
                        echo $filename ?>" />
                    </div>
                <?php }?>

					<div class="itemInfo">
                        <h2><span class="itemName">Nome:</span> <?=$post['name']?></h2>
                        <p><span class="itemName itemDescription">Descrição do item: </span> <?= ucfirst($post['description']) ?></p>
                        <p class="itemPrice">R$<?=$post['value']?>,00</p>
                        <span class="date"><?= $post['postDate'] ?></span>
                        <div class="itemButtons">
                            <form onsubmit="return submitForm(this);" action="deletePost"method="post">
                                <input type="hidden" name="postId" value="<?= $post['id'] ?>">
                                <button class="btnWarning" type="submit">Excluir</button>
                            </form>
                            <form action="editPost" method="post">
                                <input type="hidden" name="postId" value="<?= $post['id'] ?>">
                                <button type="submit">Editar</button>
                            </form>
                        </div>
                    </div>
                </div>
<?php } ?>
</section>

<script>

function submitForm() {
  return confirm('Você realmente deseja excluir?');
}

</script>