<form id="editForm" action="auth-item" method="post" enctype="multipart/form-data">
    <h1>Novo anúncio</h1>
    <input type="file" name="itemImages[]" multiple="multiple" class="images" required><br>
    <input type="text" name="name" placeholder="Nome do item" required><br>
    <input type="text" name="description" placeholder="Descrição e características do item"><br>
    <input type="text" name="contact" placeholder="Contato" required><br>
    <input type="number" name="value" placeholder="Valor" required><br>
    <button type="submit" id="insert">Criar</button>
</form>

<div class="success">
<h4><?php 
        if(isset($_GET['status']) && $_GET['status'] === 'success') {
            echo "Anúncio cadastrado com sucesso!";
        }
        ?></h4>
</div>

<div class="tips center">
    <p>Formatos aceitos: '.jpg, .jpeg .gif'</p>
    <p>Tamanho Máximo: 5 Mb.</p>
</div>