<div id="userArea">
    <p id="usrname"><span>Usuário:</span> <?= ucfirst($_SESSION['name']) ?></p>    
    <a href="/exit"><button class="btnWarning">Sair</button></a>
<hr>
</div>
<form id="searchArea" action="/search" method="post">
    <input type="text" name="search" id="" placeholder="Pesquisar" required>
    <button type="submit">Pesquisar</button>
</form>
<div class="btnTimeline">
    <a href="/register-item"><button>Novo anúncio</button></a>
    <a href="/my-itens"><button>Meus anúncios</button></a>
</div>

<h1>Timeline</h1>

<section class='showOff'>
<?php foreach($this->view->userItens as $post) { ?>
				<div class="itemArea">
                <?php

                $dirname = $post['anouncePath'];
                
                $filenames = glob("$dirname*.{jpg,jpeg,png,gif}", GLOB_BRACE);

                foreach ($filenames as $filename)
                {
                    ?>
                    
                    <div class="portrait" onclick="openModal(this)">
                        <img class="itemImage" src="<?php 
                        $filename = str_replace('../public', '', $filename);            
                        echo $filename ?>" />
                    </div>
                <?php }?>

					<div class="itemInfo">
                        <h1><span class="itemName">Anunciante: </span><?= ucwords($post['username']) ?></h1>
                        <h2><span class="itemName">Nome: </span> <?= ucwords($post['name']) ?></h2>
                        <p><span class="itemName itemDescription">Descrição do item: </span> <?= ucfirst($post['description']) ?></p>
                        <p class="itemPrice">R$ <?= number_format($post['value'], 2, ',', '.') ?></p>
                        <span class="date"><?= $post['postDate'] ?></span>
						<br />
                    </div>
                </div>
<?php } ?>
</section>