<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fastsell | <?= $this->view->title ?></title>
    <link rel="stylesheet" href="/assets/css/reset.css">
    <link rel="stylesheet" href="/assets/css/style.css">
</head>

<body>

    <button id="responsive-menu">|||</button>
    <nav id="nav">
        <ul>
            <li><a href="/timeline">Início</a></li>
            <li><a href="/login">Entrar</a></li>
            <li><a href="/register">Cadastrar</a></li>
            <li><a href="/about-us">Sobre</a></li>
            <li><a href="/contact">Contato</a></li>
            <li><a href="/about-us">FAQ</a></li>
        </ul>    
    </nav>

    <div id="conteudo">

        <?= $this->content(); ?>

    </div>

    <footer>FastSell - 2019 | Todos os direitos reservados.</footer>
    <script src="/assets/js/js.js"></script>
</body>
</html>